services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./www:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # command: sh -c "sudo chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certificado:/etc/nginx/certificado  # monta os certificados
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pjap_candidates
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gseresuser
      MYSQL_PASSWORD: Gseres@12345
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-horizon
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    command: php artisan horizon
    depends_on:
      - redis
      - app
    volumes:
      - ./www:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
